/************************** 新核心 ***********************/
SELECT  A.ACCOUNT_CODE,A.POLICY_ID,A.INTEREST_CAPITAL insuaccbala,
      (SELECT POLICY_CODE FROM APP___PAS__DBUSER.T_CONTRACT_MASTER WHERE A.POLICY_ID=POLICY_ID) contno,
      (SELECT FUND_NAME FROM APP___PAS__DBUSER.T_FUND WHERE FUND_CODE=A.ACCOUNT_CODE) accname,
      NVL(A.CREATE_DATE,A.INSERT_TIME) accfounddate,
      (SELECT MAX(SETTLE_DATE) FROM APP___PAS__DBUSER.T_FUND_SETTLEMENT 
        WHERE INVEST_ID=A.LIST_ID AND SETTLE_DATE <= SYSDATE ) lastbaladate,
      (SELECT CUSTOMER_NAME FROM APP___PAS__DBUSER.T_CUSTOMER WHERE CUSTOMER_ID=
        (SELECT CUSTOMER_ID FROM APP___PAS__DBUSER.T_POLICY_HOLDER WHERE POLICY_ID=A.POLICY_ID)) bankaccname,
      (SELECT 1 FROM APP___PAS__DBUSER.T_CONTRACT_MASTER WHERE CHANNEL_TYPE='8' AND POLICY_ID=A.POLICY_ID) AS web_sale_count,
      (SELECT 1 FROM APP___PAS__DBUSER.T_BUSINESS_PRODUCT WHERE PRODUCT_CATEGORY1='20003' AND BUSINESS_PRD_ID=
        (SELECT BUSI_PRD_ID FROM APP___PAS__DBUSER.T_CONTRACT_BUSI_PROD WHERE BUSI_ITEM_ID=A.BUSI_ITEM_ID)) AS universal_count   
      FROM APP___PAS__DBUSER.T_CONTRACT_INVEST A WHERE A.POLICY_ID=
        (SELECT POLICY_ID FROM APP___PAS__DBUSER.T_CONTRACT_MASTER WHERE POLICY_CODE='887372366079')
/************************** 老核心 ***********************/

        
