SELECT A.AGENT_CODE,A.SERVICE_TYPE,A.APPLY_TIME,B.POLICY_CODE,C.ACCEPT_STATUS,
      (SELECT STATUS_DESC FROM APP___PAS__DBUSER.T_ACCEPT_STATUS WHERE ACCEPT_STATUS=C.ACCEPT_STATUS) AS accept_status_name,
      (SELECT CHANGE_STATUS FROM APP___PAS__DBUSER.T_CHANGE WHERE A.CHANGE_ID=CHANGE_ID) AS change_status,
      B.ENDORSE_CODE ,A.AGENT_CERTI_TYPE ,B.FEE_AMOUNT ,A.INSERT_BY ,A.ORGAN_CODE ,
      (SELECT ORGAN_NAME FROM APP___PAS__DBUSER.T_UDMP_ORG WHERE A.ORGAN_CODE=ORGAN_CODE) AS organ_name,
      (SELECT REAL_NAME FROM APP___PAS__DBUSER.T_UDMP_USER WHERE USER_ID=C.UPDATE_BY) AS real_name,
      C.ACCEPT_CODE,B.POLICY_ID,B.SERVICE_CODE,
      (SELECT CAUSE_NAME FROM APP___PAS__DBUSER.T_REVERSAL_CAUSE WHERE REVERSAL_CAUSE=C.ROLLBACK_CAUSE) AS rollback_cause_name,
      (SELECT BACK_ENTYR_DESC FROM APP___PAS__DBUSER.T_CS_BACK_ENTYR_CAUSE WHERE C.BACK_ENTYR_CAUSE=BACK_ENTYR_CODE) AS back_entyr_desc 
      FROM APP___PAS__DBUSER.T_CS_APPLICATION A,APP___PAS__DBUSER.T_CS_POLICY_CHANGE B,APP___PAS__DBUSER.T_CS_ACCEPT_CHANGE C
      WHERE 1=1 
      AND A.CHANGE_ID=B.CHANGE_ID AND A.CHANGE_ID=C.CHANGE_ID
      AND C.ACCEPT_STATUS!='24' AND C.ACCEPT_STATUS!='25'
      AND TO_DATE(A.APPLY_TIME,'YYYY-MM-DD') >= TO_DATE('2018-06-04','YYYY-MM-DD') --#{edor_app_start_date}  2018-06-04
      AND TO_DATE(A.APPLY_TIME,'YYYY-MM-DD') <= TO_DATE('2018-06-04','YYYY-MM-DD')--#{edor_app_end_date}  2018-06-04
      --AND A.SERVICE_TYPE= ''--#{service_type}  13
      AND EXISTS(SELECT 1 FROM APP___PAS__DBUSER.T_CONTRACT_AGENT WHERE POLICY_ID=B.POLICY_ID AND AGENT_CODE= '38182161' /*#{agent_code} 38182161*/) 
      --AND B.POLICY_CODE= ''--#{policy_code} 
