SELECT COUNT(TCM.POLICY_CODE) 笔数 
 FROM DEV_PAS.T_CONTRACT_MASTER TCM
 WHERE TCM.LIABILITY_STATE = 4 
   AND TBP.LAPSE_CAUSE = '1'
 AND TCM.LAPSE_DATE = DATE '2017-12-26' --失效日期
 AND TCM.ORGAN_CODE LIKE '8647%'
 
 
SELECT TCM.POLICY_CODE,
(CASE WHEN TCM.LIABILITY_STATE = 4
      THEN 1
      ELSE 0
END) LIABILITY_STATE
 FROM DEV_PAS.T_CONTRACT_MASTER TCM
 WHERE TCM.LIABILITY_STATE = 4 
 AND TBP.LAPSE_CAUSE = '1'
 AND TCM.LAPSE_DATE = DATE '2017-12-26' --失效日期
 AND TCM.ORGAN_CODE LIKE '8647%'
 
SELECT COUNT(A.CONTNO) 笔数 
  FROM LCCONTSTATE A
 WHERE A.STATETYPE = 'AVAILABLE'
   AND A.STATE = '1'
   AND A.ContNo IN (SELECT CONTNO
                      FROM LIS.LCPOL B
                     WHERE B.CONTTYPE = '1'
                       AND B.MANAGECOM LIKE '8647%')
   AND A.STARTDATE = DATE '2006-03-08' --失效日期
                       
SELECT A.CONTNO,A.STATE
  FROM LCCONTSTATE A
 WHERE A.STATETYPE = 'AVAILABLE'
   AND A.STATE = '1'
   AND A.ContNo IN (SELECT CONTNO
                      FROM LIS.LCPOL B
                     WHERE B.CONTTYPE = '1'
                       AND B.MANAGECOM LIKE '8647%')
   AND A.STARTDATE = DATE '2006-03-08' --失效日期
                       
SELECT TRIM(T2.POLICY_CODE) AS POLICY_CODE,
       TRIM(T1.CONTNO) AS CONTNO,
       (CASE
         WHEN TO_CHAR(T2.LIABILITY_STATE) = T1.STATE THEN
          '否'
         ELSE
          '是'
       END) AS RESULT1
  FROM TMP_LIS_1006_GB T1
  FULL JOIN TMP_NCS_1006_GB@DB_185 T2
    ON TRIM(T1.CONTNO) = TRIM(T2.POLICY_CODE)
 ORDER BY T2.POLICY_CODE;
