SELECT COUNT(1) 满期终止笔数
        FROM (SELECT TBP.POLICY_CODE, TBP.BUSI_PROD_CODE, TBP.EXPIRY_DATE
                FROM DEV_PAS.T_CONTRACT_BUSI_PROD TBP
                JOIN DEV_PAS.T_CONTRACT_MASTER TCM
                  ON TBP.POLICY_CODE = TCM.POLICY_CODE
               WHERE TBP.LIABILITY_STATE = 3
                 AND (TBP.RENEW_DECISION <> 2 OR TBP.RENEW_DECISION IS NULL) --不处于续保中
                 AND TCM.ORGAN_CODE LIKE '8647%'
                 AND TBP.EXPIRY_DATE = DATE '2018-1-6'
                 AND TBP.END_CAUSE = '01') T; --终止原因为满期终止
                 
SELECT TBP.POLICY_CODE,TBP.EXPIRY_DATE,TBP.BUSI_PROD_CODE
  FROM DEV_PAS.T_CONTRACT_BUSI_PROD TBP
  JOIN DEV_PAS.T_CONTRACT_MASTER TCM
    ON TBP.POLICY_CODE = TCM.POLICY_CODE
 WHERE TBP.LIABILITY_STATE = 3
   AND (TBP.RENEW_DECISION <> 2 OR TBP.RENEW_DECISION IS NULL) --不处于续保中
   AND TCM.ORGAN_CODE LIKE '8647%'
   AND TBP.EXPIRY_DATE = DATE '2018-1-6'
   AND TBP.END_CAUSE = '01'; --终止原因为满期终止
   
   SELECT  COUNT(1) 满期终止笔数
  FROM LIS.LCPOL A
 INNER JOIN LIS.LCCONT C
    ON A.CONTNO = C.CONTNO
  LEFT JOIN LIS.LCCONTSTATE B
    ON A.CONTNO = B.CONTNO
   AND A.POLNO = B.POLNO
 WHERE C.MANAGECOM LIKE '8647%'
   AND B.MAKEDATE = DATE '2018-1-5'
   AND B.STATEREASON = '01'--终止原因满期终止
   AND C.CONTTYPE = '1'
   AND  B.STATETYPE = 'TERMINATE'
   ORDER BY C.CONTNO;
   
SELECT C.CONTNO,B.MAKEDATE,A.RISKCODE
  FROM LIS.LCPOL A
 INNER JOIN LIS.LCCONT C
    ON A.CONTNO = C.CONTNO
  LEFT JOIN LIS.LCCONTSTATE B
    ON A.CONTNO = B.CONTNO
   AND A.POLNO = B.POLNO
 WHERE C.MANAGECOM LIKE '8647%'
   AND B.MAKEDATE = DATE '2018-1-5'
   AND B.STATEREASON = '01'--终止原因满期终止
   AND C.CONTTYPE = '1'
   AND  B.STATETYPE = 'TERMINATE'
   ORDER BY C.CONTNO;
   
   SELECT TRIM(T2.POLICY_CODE) AS POLICY_CODE,
              TRIM(T1.CONTNO) AS CONTNO,
             (CASE
               WHEN T2.EXPIRY_DATE = T1.MAKEDATE THEN
                '否'
               ELSE
                '是'
             END) AS RESULT1
       FROM TMP_LIS_1007_GB T1
       FULL JOIN TMP_NCS_1007_GB@DB_185 T2
            ON TRIM(T1.CONTNO) = TRIM(T2.POLICY_CODE)
       ORDER BY T2.POLICY_CODE;
