SELECT COUNT(1) 终止笔数
  FROM DEV_PAS.T_CONTRACT_BUSI_PROD    TCBP,
       DEV_PAS.T_CONTRACT_PRODUCT      TCP,
       DEV_PAS.T_POLICY_ACCOUNT_STREAM TPAS
 WHERE 1 = 1
   AND TCBP.LIABILITY_STATE = 2 --险种状态 中止
   AND TPAS.ACCOUNT_TYPE = 4 ---贷款
   AND TCBP.POLICY_ID = TPAS.POLICY_ID
   AND TPAS.REGULAR_REPAY = 0 --贷款未清偿
   AND TCBP.END_CAUSE IN ('10','13') --终止原因
   AND TCP.BUSI_ITEM_ID = TCBP.BUSI_ITEM_ID
   AND TCP.ORGAN_CODE LIKE '8647%' --机构编号
   AND TCBP.EXPIRY_DATE = DATE '2017-12-26' --终止日期
   
SELECT TCBP.POLICY_CODE     AS POLICY_CODE,
       TCBP.LIABILITY_STATE AS LIABILITY_STATE,
       TCBP.END_CAUSE       AS END_CAUSE
  FROM DEV_PAS.T_CONTRACT_BUSI_PROD    TCBP,
       DEV_PAS.T_CONTRACT_PRODUCT      TCP,
       DEV_PAS.T_POLICY_ACCOUNT_STREAM TPAS
 WHERE 1 = 1
   AND TCBP.LIABILITY_STATE = 2 --险种状态
   AND TPAS.ACCOUNT_TYPE = 4 ---贷款
   AND TCBP.POLICY_ID = TPAS.POLICY_ID
   AND TPAS.REGULAR_REPAY = 0 --贷款未清偿
   AND TCBP.END_CAUSE IN ('10','13') --终止原因 DZ
   AND TCP.BUSI_ITEM_ID = TCBP.BUSI_ITEM_ID
   AND TCP.ORGAN_CODE LIKE '8647%' --机构编号
   AND TCBP.EXPIRY_DATE = DATE '2017-12-26' --终止日期
   
SELECT COUNT(A.CONTNO) 总笔数
  FROM LIS.LCCONTSTATE A
 WHERE A.STATETYPE = 'Terminate'
   AND A.STATE = '1'
   AND A.STATEREASON IN ('05','06') --自垫、贷款终止                 
   AND A.STARTDATE = DATE '2017-12-26'
   AND A.CONTNO IN (SELECT CONTNO
                      FROM LIS.LCPOL B
                     WHERE B.CONTTYPE = '1'
                       AND B.MANAGECOM LIKE '8647%')
                       
SELECT A.CONTNO, A.STATETYPE,
(CASE  WHEN A.STATEREASON = '05' THEN '13'
       ELSE A.STATEREASON
 END) AS STATEREASON
  FROM LIS.LCCONTSTATE A
 WHERE A.STATETYPE = 'Terminate'
   AND A.STATE = '1'
   AND A.STATEREASON IN ('05','06') --自垫、贷款终止                
   AND A.STARTDATE = DATE'2017-12-26'
   AND A.CONTNO IN (SELECT CONTNO
                      FROM LIS.LCPOL B
                     WHERE B.CONTTYPE = '1'
                       AND B.MANAGECOM LIKE '8647%');
                       
SELECT TRIM(T2.POLICY_CODE) AS POLICY_CODE,
       TRIM(T1.CONTNO) AS CONTNO,
       (CASE
         WHEN T2.END_CAUSE = T1.STATEREASON THEN
          '否'
         ELSE
          '是'
       END) AS RESULT1 --是否差异
  FROM TMP_LIS_1004_GB T1
  FULL JOIN TMP_NCS_1004_GB@DB_185 T2
    ON TRIM(T1.CONTNO) = TRIM(T2.POLICY_CODE)
 ORDER BY T2.POLICY_CODE;
 
