SELECT COUNT(1) 终止笔数
  FROM DEV_PAS.T_CONTRACT_BUSI_PROD    TCBP,
       DEV_PAS.T_CONTRACT_PRODUCT      TCP
 WHERE 1 = 1
   AND TCBP.LIABILITY_STATE = '4' --险种状态
   AND TCBP.LAPSE_CAUSE = '2' --终止原因 投连
   AND TCP.BUSI_ITEM_ID = TCBP.BUSI_ITEM_ID
   AND TCP.ORGAN_CODE LIKE '8647%' --机构编号
   AND TCBP.EXPIRY_DATE = DATE '2017-12-26' --终止日期
   
   CREATE TABLE  APP___PAS__DBUSER.TMP_NCS_1001_GB  AS
--DELETE FROM TMP_NCS_1001_GB;
--COMMIT;
--INSERT INTO TMP_NCS_1001_GB
SELECT TCBP.POLICY_CODE     AS POLICY_CODE,
       TCBP.LIABILITY_STATE AS LIABILITY_STATE,
       TCBP.END_CAUSE       AS END_CAUSE
  FROM DEV_PAS.T_CONTRACT_BUSI_PROD    TCBP,
       DEV_PAS.T_CONTRACT_PRODUCT      TCP
 WHERE 1 = 1
   AND TCBP.LIABILITY_STATE = '3' --险种状态
   AND TCBP.END_CAUSE = '11' --终止原因
   AND TCP.BUSI_ITEM_ID = TCBP.BUSI_ITEM_ID
   AND TCP.ORGAN_CODE LIKE '8647%' --机构编号
   AND TCBP.EXPIRY_DATE = DATE '2017-12-26' --终止日期
   
SELECT COUNT(A.CONTNO) 总笔数
  FROM LIS.LCCONTSTATE A
 WHERE A.STATETYPE = 'Terminate'
   AND A.STATE = '1'
   AND A.STATEREASON IN ('05' --自垫终止 
                        ,
                         '06') --贷款终止                 
   AND A.STARTDATE = DATE '2017-12-26'
   AND A.CONTNO IN (SELECT CONTNO
                      FROM LIS.LCPOL B
                     WHERE B.CONTTYPE = '1'
                       AND B.MANAGECOM LIKE '8647%')
