SEND_PACKAGE_TIME --发包时间
RECEIVED_PACKAGE_TIME --回传时间
SEND_STATE --发送状态
RECEIVE_STATE --返回状态
T_OUTSOURCE_CASE --外包案件信息表
CASE_ID --赔案ID
CASE_NO --赔案号

SELECT DISTINCT TCM.POLICY_CODE 保单号,
        TCM.ORGAN_CODE 管理机构,
        TOC.SEND_STATE 发送状态,
        TOC.RECEIVE_STATE 返回状态
FROM  DEV_CLM.T_OUTSOURCE_CASE TOC
  LEFT JOIN DEV_CLM.T_CONTRACT_MASTER TCM
  ON TCM.CASE_ID = TOC.CASE_ID
WHERE 1 = 1
--AND SEND_PACKAGE_TIME = DATE '2018-05-28'
AND TCM.ORGAN_CODE LIKE '8647%'
--GROUP BY TCM.POLICY_CODE
ORDER BY TCM.POLICY_CODE

SELECT COUNT(1) 发送件数 FROM 
(SELECT TCM.POLICY_CODE
  FROM  DEV_CLM.T_OUTSOURCE_CASE TOC
    LEFT JOIN DEV_CLM.T_CONTRACT_MASTER TCM
    ON TCM.CASE_ID = TOC.CASE_ID
  WHERE 1 = 1
  TOC.SEND_PACKAGE_TIME = DATE '2018-05-28'
  AND TCM.ORGAN_CODE LIKE '8647%'
GROUP BY TCM.POLICY_CODE);

SELECT COUNT(1) 回传件数 FROM 
(SELECT TCM.POLICY_CODE
  FROM  DEV_CLM.T_OUTSOURCE_CASE TOC
    LEFT JOIN DEV_CLM.T_CONTRACT_MASTER TCM
    ON TCM.CASE_ID = TOC.CASE_ID
  WHERE 1 = 1
  TOC.RECEIVED_PACKAGE_TIME = DATE '2018-05-28'
  AND TCM.ORGAN_CODE LIKE '8647%'
GROUP BY TCM.POLICY_CODE);

/********************************************* 新核心统计 ************************************************/
SELECT 
       (CASE WHEN ROWNUM = 1 THEN 
             (SELECT COUNT(1) FROM 
                (SELECT TCM.POLICY_CODE
                  FROM  DEV_CLM.T_OUTSOURCE_CASE TOC
                    LEFT JOIN DEV_CLM.T_CONTRACT_MASTER TCM
                    ON TCM.CASE_ID = TOC.CASE_ID
                  WHERE 1 = 1
                  AND TOC.SEND_PACKAGE_TIME = DATE '2018-05-28' --发送日期
                  AND TCM.ORGAN_CODE LIKE '8647%' --管理机构
                GROUP BY TCM.POLICY_CODE)) 
        END) 发送件数,
       (CASE WHEN ROWNUM = 1 THEN 
             (SELECT COUNT(1) FROM 
                (SELECT TCM.POLICY_CODE
                  FROM  DEV_CLM.T_OUTSOURCE_CASE TOC
                    LEFT JOIN DEV_CLM.T_CONTRACT_MASTER TCM
                    ON TCM.CASE_ID = TOC.CASE_ID
                  WHERE 1 = 1
                  AND TOC.RECEIVED_PACKAGE_TIME = DATE '2018-05-28' --发送日期
                  AND TCM.ORGAN_CODE LIKE '8647%' --管理机构
                GROUP BY TCM.POLICY_CODE)) 
        END) 回传件数
       FROM DEV_CLM.T_OUTSOURCE_CASE
WHERE ROWNUM = 1;  
/********************************************* 新核心明细 ************************************************/
SELECT DISTINCT TCM.POLICY_CODE 保单号,
        TCM.ORGAN_CODE 管理机构,
        TOC.SEND_STATE 发送状态,
        TOC.RECEIVE_STATE 返回状态
FROM  DEV_CLM.T_OUTSOURCE_CASE TOC
  LEFT JOIN DEV_CLM.T_CONTRACT_MASTER TCM
  ON TCM.CASE_ID = TOC.CASE_ID
WHERE 1 = 1
AND (TCO.SEND_PACKAGE_TIME = DATE '2018-05-28' OR --发送日期
    TOC.RECEIVED_PACKAGE_TIME = DATE '2018-05-28') --回传日期
AND TCM.ORGAN_CODE LIKE '8647%'
ORDER BY TCM.POLICY_CODE;
