SELECT T.PUB_SRV_CODE, T.MSG_ID,T.REQ_TRAN_DATA,T.OLD_RES_TRAN_DATA, T.NEW_RES_TRAN_DATA ,ROUTER_EXCEPTION
  FROM ESBJK.SRV_SERVICE_DISPOSE_LOG_DATA T 
 WHERE T.OLD_RES_TRAN_DATA IS NOT NULL 
   and T.MSG_ID = '0b11638e-4dbd-41e1-9104-e7a6f551c440'
