SELECT   COUNT(DISTINCT TCM.POLICY_CODE) AS 笔数,
       SUM(TPB.FEE_AMOUNT) AS 总金额
  FROM DEV_PAS.T_CONTRACT_MASTER@BINGXING_168_15   TCM,
       DEV_PAS.T_PERSISTENCE_BONUS@BINGXING_168_15 TPB
 WHERE 1 = 1
   AND TCM.POLICY_ID = TPB.POLICY_ID
   AND TPB.PROCESS_STATUS = 1 --交易成功
   AND TCM.ORGAN_CODE LIKE '8647%'
   --支付日期
   AND TPB.PAY_DUE_DATE = TRUNC(SYSDATE)-1;
   
SELECT   COUNT(DISTINCT A.CONTNO) AS 笔数,SUM(A.MONEY) AS 总金额
  FROM LIS.LCINSUREACCTRACE A
 WHERE A.CONTNO IN (SELECT CONTNO
                      FROM LIS.LCPOL B
                     WHERE B.CONTTYPE = '1'
                       AND B.MANAGECOM LIKE '8647%')
       AND FEECODE IN ('904004','905002','903004','907002','907007','907008','909002','909007')                 
       AND A.PAYDATE = TRUNC(SYSDATE)-1; --实际支付日期
       -- A.VALUEDATE = TRUNC(SYSDATE);


/*****************************************************************  明细 **********************************************************/       
--CREATE TABLE  TMP_NCS_1009  AS
DELETE FROM TMP_NCS_1009;
COMMIT;
INSERT INTO TMP_NCS_1009
SELECT   TCM.POLICY_CODE, --保单号
       SUM(TPB.FEE_AMOUNT) FEE_AMOUNT --金额
  FROM DEV_PAS.T_CONTRACT_MASTER@BINGXING_168_15   TCM,
       DEV_PAS.T_PERSISTENCE_BONUS@BINGXING_168_15 TPB
 WHERE 1 = 1
   AND TCM.POLICY_ID = TPB.POLICY_ID
   AND TPB.PROCESS_STATUS = 1 --交易成功
   AND TCM.ORGAN_CODE LIKE '8647%'
   AND TPB.PAY_DUE_DATE = TRUNC(SYSDATE)-1 --支付日期
 GROUP BY TCM.POLICY_CODE
 ORDER BY TCM.POLICY_CODE;
 COMMIT;
 
--CREATE TABLE TMP_LIS_1009 AS
DELETE FROM TMP_LIS_1009;
COMMIT;
INSERT INTO TMP_LIS_1009
SELECT   A.CONTNO,SUM(A.MONEY) MONEY
  FROM LIS.LCINSUREACCTRACE A
   WHERE FEECODE IN ('904004','905002','903004','907002','907007','907008','909002','909007') 
       AND A.CONTNO IN (SELECT CONTNO
                      FROM LIS.LCPOL B
                     WHERE B.CONTTYPE = '1'
                       AND B.MANAGECOM LIKE '8647%')
       --AND A.VALUEDATE = DATE '2012-09-26' --实际支付日期
       AND PAYDATE = TRUNC(SYSDATE)-1
 GROUP BY A.CONTNO
 ORDER BY A.CONTNO;
COMMIT;

SELECT   NVL(TRIM(T2.POLICY_CODE),TRIM(T1.CONTNO)) AS 保单号,
      T2.FEE_AMOUNT AS 新核心金额,
      T1.MONEY AS 老核心金额,
      NVL(T2.FEE_AMOUNT,0) - NVL(T1.MONEY,0) AS 差异值
FROM TMP_LIS_1009 T1
FULL JOIN TMP_NCS_1009 T2
  ON TRIM(T1.CONTNO) = TRIM(T2.POLICY_CODE)
ORDER BY T2.POLICY_CODE;




