SELECT   COUNT(1) AS 新核心保单件数
  FROM (SELECT DISTINCT TCBP.POLICY_CODE, -- 保单号
                        TCBP.BUSI_PROD_CODE, -- 产品编码
                        TCP.PRODUCT_CODE, -- 责任组编码
                        TCP.AMOUNT -- 生效后保额
          FROM DEV_PAS.T_CONTRACT_BUSI_PROD@BINGXING_168_15 TCBP,
               DEV_PAS.T_PRECONT_PRODUCT@BINGXING_168_15    TPP,
               DEV_PAS.T_CONTRACT_PRODUCT@BINGXING_168_15   TCP
         WHERE TCBP.BUSI_ITEM_ID = TCP.BUSI_ITEM_ID
           AND TPP.BUSI_ITEM_ID = TCP.BUSI_ITEM_ID
           AND TCP.ORGAN_CODE LIKE '8647%'
           AND TPP.PRECONT_TIME = TRUNC(SYSDATE)-1
           AND TPP.PRECONT_STATUS = '1');
           

SELECT   COUNT(*) AS 老核心保单件数
  FROM LIS.LCPOLOTHER
  LEFT JOIN LIS.LCCONT
    ON LCPOLOTHER.CONTNO = LCCONT.CONTNO
  LEFT JOIN LIS.LCPOL
    ON LCPOLOTHER.CONTNO = LCPOL.CONTNO
   AND LCPOLOTHER.POLNO = LCPOL.POLNO
  LEFT JOIN LIS.LCDUTY
    ON LCPOLOTHER.POLNO = LCDUTY.POLNO
 WHERE LCPOLOTHER.P1 IS NOT NULL
   AND LCPOLOTHER.P2 IS NOT NULL
   AND LCPOLOTHER.P3 IS NOT NULL
   AND LCPOLOTHER.P4 IS NOT NULL
   AND LCPOL.RISKCODE = '00909000'
   AND LCPOL.APPFLAG = '1'
   AND LCCONT.MANAGECOM LIKE '8647%'  --机构
   AND ADD_MONTHS(LCPOL.CVALIDATE,
                  (LCPOLOTHER.P2 - LCPOL.INSUREDAPPAGE) * 12) = TRUNC(SYSDATE)-1; --统计日期 = 客户约定年龄的保单生效日
                  
                  
/**************************************************** 明细 ************************************************************/

--CREATE TABLE TMP_NCS_1010 AS
DELETE FROM TMP_NCS_1010;
COMMIT;
INSERT INTO TMP_NCS_1010
  SELECT   DISTINCT TCBP.POLICY_CODE, -- 保单号
                TCBP.BUSI_PROD_CODE, -- 产品编码
                TCP.PRODUCT_CODE, -- 责任组编码
                TCP.AMOUNT -- 生效后保额
  FROM DEV_PAS.T_CONTRACT_BUSI_PROD@BINGXING_168_15 TCBP,
       DEV_PAS.T_PRECONT_PRODUCT@BINGXING_168_15    TPP,
       DEV_PAS.T_CONTRACT_PRODUCT@BINGXING_168_15   TCP
 WHERE TCBP.BUSI_ITEM_ID = TCP.BUSI_ITEM_ID
   AND TPP.BUSI_ITEM_ID = TCP.BUSI_ITEM_ID
   AND TCP.ORGAN_CODE LIKE '8647%'
   AND TPP.PRECONT_TIME = TRUNC(SYSDATE)-1
   AND TPP.PRECONT_STATUS = '1';
COMMIT;

--CREATE TABLE TMP_LIS_1010 AS
DELETE FROM TMP_LIS_1010;
COMMIT;
INSERT INTO TMP_LIS_1010
  SELECT   LCPOLOTHER.CONTNO, -- 保单号
         LCPOL.RISKCODE, -- 产品编码
         LCDUTY.DUTYCODE, -- 责任组编码
         TO_NUMBER(LCPOLOTHER.P4) AS AMOUNT -- 预约生效后的基本保额
    FROM LIS.LCPOLOTHER
    LEFT JOIN LIS.LCCONT
      ON LCPOLOTHER.CONTNO = LCCONT.CONTNO
    LEFT JOIN LIS.LCPOL
      ON LCPOLOTHER.CONTNO = LCPOL.CONTNO
     AND LCPOLOTHER.POLNO = LCPOL.POLNO
    LEFT JOIN LIS.LCDUTY
      ON LCPOLOTHER.POLNO = LCDUTY.POLNO
   WHERE LCPOLOTHER.P1 IS NOT NULL
     AND LCPOLOTHER.P2 IS NOT NULL
     AND LCPOLOTHER.P3 IS NOT NULL
     AND LCPOLOTHER.P4 IS NOT NULL
     AND LCPOL.RISKCODE = '00909000'
     AND LCPOL.APPFLAG = '1'
     AND LCCONT.MANAGECOM LIKE '8647%'  --机构
     AND ADD_MONTHS(LCPOL.CVALIDATE,
                    (LCPOLOTHER.P2 - LCPOL.INSUREDAPPAGE) * 12) = TRUNC(SYSDATE)-1; --统计日期 = 客户约定年龄的保单生效日
COMMIT;

SELECT   CASE
         WHEN TRIM(T1.CONTNO) = TRIM(T2.POLICY_CODE) THEN
          TRIM(T1.CONTNO)
         WHEN TRIM(T1.CONTNO) IS NULL THEN
          TRIM(T2.POLICY_CODE)
         ELSE
          TRIM(T1.CONTNO)
       END AS 保单号,
       CASE
         WHEN TRIM(T1.RISKCODE) = TRIM(T2.BUSI_PROD_CODE) THEN
          TRIM(T1.RISKCODE)
         WHEN TRIM(T1.RISKCODE) IS NULL THEN
          TRIM(T2.BUSI_PROD_CODE)
         ELSE
          TRIM(T1.RISKCODE)
       END AS 产品编码,
       CASE
         WHEN TRIM(T1.DUTYCODE) = TRIM(T2.PRODUCT_CODE) THEN
          TRIM(T1.DUTYCODE)
         WHEN TRIM(T1.DUTYCODE) IS NULL THEN
          TRIM(T2.PRODUCT_CODE)
         ELSE
          TRIM(T1.DUTYCODE)
       END AS 责任组编码,
       NVL(T1.AMOUNT, 0) AS 老核心生效后保额,
       NVL(T2.AMOUNT, 0) AS 新核心生效后保额,
       NVL(T1.AMOUNT, 0) - NVL(T2.AMOUNT, 0) AS 差异
  FROM TMP_LIS_1010 T1
  FULL JOIN TMP_NCS_1010 T2
    ON TRIM(T1.CONTNO) = TRIM(T2.POLICY_CODE)
   AND TRIM(T1.RISKCODE) = TRIM(T2.BUSI_PROD_CODE)
   AND TRIM(T1.DUTYCODE) = TRIM(T2.PRODUCT_CODE)
 ORDER BY T2.POLICY_CODE;




