SELECT COUNT(1) AS 终止笔数
  FROM DEV_PAS.T_CONTRACT_BUSI_PROD@BINGXING_168_15    TCBP,
       DEV_PAS.T_CONTRACT_PRODUCT@BINGXING_168_15      TCP,
       DEV_PAS.T_POLICY_ACCOUNT_STREAM@BINGXING_168_15 TPAS
 WHERE 1 = 1
   AND TCBP.LIABILITY_STATE = '3' --险种状态
   AND TPAS.ACCOUNT_TYPE = '4' ---贷款
   AND TCBP.POLICY_ID = TPAS.POLICY_ID
   AND TPAS.REGULAR_REPAY = '0' --贷款未清偿
   AND TCBP.END_CAUSE = '06' --终止原因
   AND TCP.BUSI_ITEM_ID = TCBP.BUSI_ITEM_ID
   AND TCP.ORGAN_CODE LIKE '8647%' --机构编号
   --终止日期
   AND TCBP.EXPIRY_DATE = TRUNC(SYSDATE)-1; 

SELECT COUNT(A.CONTNO) AS 批处理笔数
  FROM LIS.LCCONTSTATE A
 WHERE A.STATETYPE = 'Terminate'
   AND A.STATE = '1'
   AND A.STATEREASON IN ('05' ,'06') --自垫终止 贷款终止                 
   AND A.STARTDATE = TRUNC(SYSDATE)-1
   AND A.CONTNO IN (SELECT CONTNO
                      FROM LIS.LCPOL B
                     WHERE B.CONTTYPE = '1'
                       AND B.MANAGECOM LIKE '8647%');

                       
DELETE FROM TMP_NCS_1003;
COMMIT;
INSERT INTO TMP_NCS_1003
--CREATE TABLE  TMP_NCS_1003  AS
SELECT TCBP.POLICY_CODE, --保单号
       TCBP.LIABILITY_STATE, --效力状态
       TCBP.END_CAUSE --终止原因
  FROM DEV_PAS.T_CONTRACT_BUSI_PROD@BINGXING_168_15 TCBP,
       DEV_PAS.T_CONTRACT_PRODUCT@BINGXING_168_15 TCP,
       DEV_PAS.T_POLICY_ACCOUNT_STREAM@BINGXING_168_15 TPAS
 WHERE 1 = 1
   AND TCBP.LIABILITY_STATE = '3' --险种状态
   AND TPAS.ACCOUNT_TYPE = '4' ---贷款
   AND TCBP.POLICY_ID = TPAS.POLICY_ID
   AND TPAS.REGULAR_REPAY = '0' --贷款未清偿
   AND TCBP.END_CAUSE = '06' --终止原因
   AND TCP.BUSI_ITEM_ID = TCBP.BUSI_ITEM_ID
   AND TCP.ORGAN_CODE LIKE '8647%' --机构编号
    --终止日期
   AND TCBP.EXPIRY_DATE = TRUNC(SYSDATE)-1; 
COMMIT;


DELETE FROM TMP_LIS_1003;
COMMIT;
INSERT INTO TMP_LIS_1003
--CREATE TABLE  TMP_LIS_1003 AS
SELECT  A.CONTNO AS CONTNO, A.STATETYPE AS STATETYPE, A.STATEREASON AS STATEREASON
  FROM LIS.LCCONTSTATE A
 WHERE A.STATETYPE = 'Terminate'
   AND A.STATE = '1'
   AND A.STATEREASON IN ('05' --自垫终止
                                            ,'06') --贷款终止                 
   AND A.STARTDATE = TRUNC(SYSDATE)-1
   AND A.CONTNO IN (SELECT /*+ parallel(50) */ CONTNO
                      FROM LIS.LCPOL B
                     WHERE B.CONTTYPE = '1'
                       AND B.MANAGECOM LIKE '8647%');
COMMIT;


SELECT  NVL(TRIM(T2.POLICY_CODE),TRIM(T1.CONTNO)) 保单号,
       T1.STATETYPE 老核心效力状态,
       T1.STATEREASON 老核心终止原因 ,
       T2.LIABILITY_STATE 新核心效力状态 ,
       T2.END_CAUSE 新核心终止原因,
       CASE WHEN T1.STATETYPE=T2.LIABILITY_STATE AND T1.STATEREASON=T2.END_CAUSE 
              THEN   '否'
            ELSE '是'
       END  是否差异
  FROM TMP_LIS_1003 T1
  FULL JOIN TMP_NCS_1003 T2
    ON TRIM(T1.CONTNO) = TRIM(T2.POLICY_CODE)
 ORDER BY T2.POLICY_CODE;



