SELECT   COUNT(1) AS 新核心保单险种超限终止件数
  FROM (SELECT DISTINCT TCBP.POLICY_CODE,
                        TCBP.BUSI_PROD_CODE,
                        TCBP.LIABILITY_STATE,
                        TCBP.END_CAUSE
          FROM DEV_PAS.T_CONTRACT_BUSI_PROD@BINGXING_168_15 TCBP,
               DEV_PAS.T_CONTRACT_MASTER@BINGXING_168_15    TCM
         WHERE TCBP.END_CAUSE = '14'
           AND TCBP.LIABILITY_STATE = '3'
           AND TCM.POLICY_ID = TCBP.POLICY_ID
           AND TCM.ORGAN_CODE LIKE '8647%'
           AND TCBP.EXPIRY_DATE = TRUNC(SYSDATE)-1);
           
SELECT   COUNT(*) AS 老核心保单险种超限终止件数
  FROM LIS.LCCONTSTATE
 INNER JOIN LIS.LCPOL
    ON LCCONTSTATE.CONTNO = LCPOL.CONTNO
   AND LCCONTSTATE.POLNO = LCPOL.POLNO
  LEFT JOIN LIS.LCCONT
    ON LCCONT.CONTNO = LCCONTSTATE.CONTNO
  LEFT JOIN (SELECT CODETYPE, OLD_CODE, NEW_CODE
               FROM T_CODEMAPPING
              WHERE CODETYPE = 'LIABILITY_STATE'
                AND FROM_MODLE = 'PAS'
                AND FLAG = '1') CODEMAPPING_STATE
    ON CODEMAPPING_STATE.OLD_CODE = LCPOL.APPFLAG
  LEFT JOIN (SELECT CODETYPE, OLD_CODE, NEW_CODE
               FROM T_CODEMAPPING
              WHERE CODETYPE = 'END_CAUSE'
                AND FROM_MODLE = 'PAS'
                AND FLAG = '1') CODEMAPPING_END_CAUSE
    ON TRIM(CODEMAPPING_END_CAUSE.OLD_CODE) = TRIM(LCCONTSTATE.STATEREASON)
 WHERE LCPOL.RISKCODE IN ('00555000', '00556000')
   AND LCPOL.APPFLAG = '4'
   AND LCCONTSTATE.STATETYPE = 'Terminate'
   AND LCCONTSTATE.STATE = '1'
   AND LCCONT.MANAGECOM LIKE '8647%' --机构
   AND LCCONTSTATE.STARTDATE = TRUNC(SYSDATE)-1;
   
/***************************************************** 明细 *******************************************************/
--CREATE TABLE  TMP_NCS_1011 AS
DELETE FROM TMP_NCS_1011;
COMMIT;
INSERT INTO TMP_NCS_1011
 SELECT   DISTINCT TCBP.POLICY_CODE, --保单号
                 TCBP.BUSI_PROD_CODE, --产品编码
                 TCBP.LIABILITY_STATE, --效力状态
                 TCBP.END_CAUSE --终止原因
   FROM DEV_PAS.T_CONTRACT_BUSI_PROD@BINGXING_168_15 TCBP,
        DEV_PAS.T_CONTRACT_MASTER@BINGXING_168_15    TCM
  WHERE TCBP.END_CAUSE = '14'
    AND TCBP.LIABILITY_STATE = '3'
    AND TCM.POLICY_ID = TCBP.POLICY_ID
    AND TCM.ORGAN_CODE LIKE '8647%'
    AND TCBP.EXPIRY_DATE = TRUNC(SYSDATE)-1;
COMMIT;

--CREATE TABLE TMP_LIS_1011 AS
DELETE FROM TMP_LIS_1011;
COMMIT;
INSERT INTO TMP_LIS_1011
  SELECT   LCCONTSTATE.CONTNO, -- 保单号
         LCPOL.RISKCODE, -- 产品编码
         CODEMAPPING_STATE.NEW_CODE     AS APPFLAG, -- 效力状态
         CODEMAPPING_END_CAUSE.NEW_CODE AS STATEREASON -- 终止原因
    FROM LIS.LCCONTSTATE
   INNER JOIN LIS.LCPOL
      ON LCCONTSTATE.CONTNO = LCPOL.CONTNO
     AND LCCONTSTATE.POLNO = LCPOL.POLNO
    LEFT JOIN LIS.LCCONT
      ON LCCONT.CONTNO = LCCONTSTATE.CONTNO
    LEFT JOIN (SELECT CODETYPE, OLD_CODE, NEW_CODE
                 FROM T_CODEMAPPING
                WHERE CODETYPE = 'LIABILITY_STATE'
                  AND FROM_MODLE = 'PAS'
                  AND FLAG = '1') CODEMAPPING_STATE -- 效力状态转为新核心代码
      ON CODEMAPPING_STATE.OLD_CODE = LCPOL.APPFLAG
    LEFT JOIN (SELECT CODETYPE, OLD_CODE, NEW_CODE
                 FROM T_CODEMAPPING
                WHERE CODETYPE = 'END_CAUSE'
                  AND FROM_MODLE = 'PAS'
                  AND FLAG = '1') CODEMAPPING_END_CAUSE -- 终止原因转为新核心代码
      ON TRIM(CODEMAPPING_END_CAUSE.OLD_CODE) =
         TRIM(LCCONTSTATE.STATEREASON)
   WHERE LCPOL.RISKCODE IN ('00555000', '00556000')
     AND LCPOL.APPFLAG = '4'
     AND LCCONTSTATE.STATETYPE = 'Terminate'
     AND LCCONTSTATE.STATE = '1'
     AND LCCONT.MANAGECOM LIKE '8647%' --机构
     AND LCCONTSTATE.STARTDATE =TRUNC(SYSDATE)-1;
COMMIT;

SELECT   CASE
         WHEN TRIM(T1.CONTNO) = TRIM(T2.POLICY_CODE) THEN
          TRIM(T1.CONTNO)
         WHEN TRIM(T1.CONTNO) IS NULL THEN
          TRIM(T2.POLICY_CODE)
         ELSE
          TRIM(T1.CONTNO)
       END AS 保单号,
       CASE
         WHEN TRIM(T1.RISKCODE) = TRIM(T2.BUSI_PROD_CODE) THEN
          TRIM(T1.RISKCODE)
         WHEN TRIM(T1.RISKCODE) IS NULL THEN
          TRIM(T2.BUSI_PROD_CODE)
         ELSE
          TRIM(T1.RISKCODE)
       END AS 产品编码,
       T1.APPFLAG AS 老核心效力状态,
       T1.STATEREASON AS 老核心终止原因,
       T2.LIABILITY_STATE AS 新核心效力状态,
       T2.END_CAUSE AS 新核心终止原因,
       CASE
         WHEN T1.APPFLAG = T2.LIABILITY_STATE THEN
          'Y'
         ELSE
          'N'
       END AS 差异状态
  FROM TMP_LIS_1011 T1
  FULL JOIN TMP_NCS_1011 T2
    ON TRIM(T1.CONTNO) = TRIM(T2.POLICY_CODE)
   AND TRIM(T1.RISKCODE) = TRIM(T2.BUSI_PROD_CODE)
 ORDER BY T2.POLICY_CODE;



