SELECT COUNT(1) AS 满期终止笔数
  FROM (SELECT TBP.POLICY_CODE, TBP.BUSI_PROD_CODE, TBP.LIABILITY_STATE
          FROM DEV_PAS.T_CONTRACT_BUSI_PROD@BINGXING_168_15 TBP
          JOIN DEV_PAS.T_CONTRACT_MASTER@BINGXING_168_15 TCM
            ON TBP.POLICY_CODE = TCM.POLICY_CODE
         WHERE TBP.LIABILITY_STATE = 3
           AND (TBP.RENEW_DECISION <> 2 OR TBP.RENEW_DECISION IS NULL) --不处于续保中
           AND TCM.ORGAN_CODE LIKE '8647%'
           AND TBP.EXPIRY_DATE = TRUNC(SYSDATE)-1
           --终止原因为满期终止
           AND TBP.END_CAUSE = '01') T;

           
SELECT
  COUNT(1) AS 满期终止笔数
  FROM LIS.LCPOL A
 INNER JOIN LIS.LCCONT C
    ON A.CONTNO = C.CONTNO
  LEFT JOIN LIS.LCCONTSTATE B
    ON A.CONTNO = B.CONTNO
   AND A.POLNO = B.POLNO
 WHERE C.MANAGECOM LIKE '8647%'
   AND B.MAKEDATE = TRUNC(SYSDATE)-1
   AND B.STATEREASON = '01' --终止原因满期终止
   AND C.CONTTYPE = '1'
   AND B.STATETYPE = 'Terminate'
 ORDER BY C.CONTNO;

 
/*************************************************************** 明细 ********************************************************/ 
DELETE FROM TMP_NCS_1006;
COMMIT;
INSERT INTO TMP_NCS_1006
--CREATE TABLE TMP_NCS_1006  AS
SELECT TBP.POLICY_CODE, --保单号
       TBP.BUSI_PROD_CODE, --险种编码
       TBP.LIABILITY_STATE, --效力状态
       TBP.END_CAUSE --终止原因
  FROM DEV_PAS.T_CONTRACT_BUSI_PROD@BINGXING_168_15 TBP
  JOIN DEV_PAS.T_CONTRACT_MASTER@BINGXING_168_15 TCM
    ON TBP.POLICY_CODE = TCM.POLICY_CODE
 WHERE TBP.LIABILITY_STATE = 3
   AND (TBP.RENEW_DECISION <> 2 OR TBP.RENEW_DECISION IS NULL) --不处于续保中
   AND TCM.ORGAN_CODE LIKE '8647%'
   AND TBP.EXPIRY_DATE = TRUNC(SYSDATE)-1
   --终止原因为满期终止
   AND TBP.END_CAUSE = '01'; 
COMMIT;


DELETE FROM TMP_LIS_1006;
COMMIT;
INSERT INTO TMP_LIS_1006 
--CREATE TABLE  TMP_LIS_1006 AS
SELECT 
       C.CONTNO      AS CONTNO,
       A.RISKCODE    AS RISKCODE,
       B.STATE       AS STATE,
       B.STATEREASON AS STATEREASON
  FROM LIS.LCPOL A
 INNER JOIN LIS.LCCONT C
    ON A.CONTNO = C.CONTNO
  LEFT JOIN LIS.LCCONTSTATE B
    ON A.CONTNO = B.CONTNO
   AND A.POLNO = B.POLNO
 WHERE C.MANAGECOM LIKE '8647%'
   AND B.MAKEDATE = TRUNC(SYSDATE)-1
   AND B.STATEREASON = '01' --终止原因满期终止
   AND C.CONTTYPE = '1'
   AND B.STATETYPE = 'Terminate'
   ORDER BY C.CONTNO;
COMMIT;


SELECT 
       NVL(TRIM(T2.POLICY_CODE), TRIM(T1.CONTNO)) AS 保单号,
       NVL(T1.RISKCODE, T2.BUSI_PROD_CODE) AS 产品编码,
       T1.STATE AS 老核心效力状态,
       T1.STATEREASON AS 老核心终止原因,
       T2.LIABILITY_STATE AS 新核心效力状态,
       T2.END_CAUSE AS 新核心效力原因,
      CASE WHEN (CASE WHEN T1.STATE=1
         THEN '3'
           END) =T2.LIABILITY_STATE THEN 'N'
       ELSE 'Y' END
       
        AS 差异
  FROM TMP_LIS_1006 T1
  FULL JOIN TMP_NCS_1006 T2
    ON TRIM(T1.CONTNO) = TRIM(T2.POLICY_CODE)
 ORDER BY T2.POLICY_CODE;





