SELECT   COUNT(1) AS 条数, SUM(S.SURRENDER_AMOUNT) AS 金额
  FROM DEV_PAS.T_CS_ACCEPT_CHANGE@BINGXING_168_15   A,
       DEV_PAS.T_SURRENDER@BINGXING_168_15          S,
       DEV_PAS.T_CONTRACT_BUSI_PROD@BINGXING_168_15 P
 WHERE A.ACCEPT_STATUS = '18'
   AND A.PRE_FLAG = '1'
   AND A.SERVICE_CODE = 'CT'
   AND S.ACCEPT_CODE = A.ACCEPT_CODE
   AND S.BUSI_ITEM_ID = P.BUSI_ITEM_ID
   AND A.PRE_VALIDATE_DATE = TRUNC(SYSDATE)-1
   AND A.ORGAN_CODE LIKE '8647%';
   
SELECT   COUNT(DISTINCT A.CONTNO), --件数
       SUM(C.GETMONEY) --退保总金额
  FROM LIS.LPEDORITEM A
 INNER JOIN LIS.LPEDORAPP B
    ON A.EDORACCEPTNO = B.EDORACCEPTNO
 INNER JOIN LIS.LJAGETENDORSE C
    ON A.EDORNO = C.ENDORSEMENTNO --批单号码
 WHERE A.EDORTYPE = 'CT'
   AND A.EDORSTATE = '0' --确认生效
   AND A.EDORVALIDATE = TRUNC(SYSDATE)-1
   AND B.PREINPUTFLAG = '1' --预录入保全标记
   AND EXISTS (SELECT 1
          FROM LIS.LCCONT N
         WHERE A.CONTNO = N.CONTNO
           AND N.APPFLAG IN ('1', '4') --承包和终止保单
           AND N.CONTTYPE = '1' --个单
           AND N.MANAGECOM LIKE '8647%');
           
--CREATE TABLE TMP_NCS_1028 AS
DELETE FROM TMP_NCS_1028;
COMMIT;
INSERT INTO TMP_NCS_1028
SELECT   MAX(P.POLICY_CODE) AS POLICY_CODE, --保单号
       MAX(P.BUSI_PROD_CODE) AS BUSI_PROD_CODE, --险种号
       SUM(S.SURRENDER_AMOUNT) AS SURRENDER_AMOUNT --退保金额
  FROM DEV_PAS.T_CS_ACCEPT_CHANGE@BINGXING_168_15   A,
       DEV_PAS.T_SURRENDER@BINGXING_168_15          S,
       DEV_PAS.T_CONTRACT_BUSI_PROD@BINGXING_168_15 P
 WHERE A.ACCEPT_STATUS = '18'
   AND A.PRE_FLAG = '1'
   AND A.SERVICE_CODE = 'CT'
   AND S.ACCEPT_CODE = A.ACCEPT_CODE
   AND S.BUSI_ITEM_ID = P.BUSI_ITEM_ID
   AND A.PRE_VALIDATE_DATE = TRUNC(SYSDATE)-1
   AND A.ORGAN_CODE LIKE '8647%';
COMMIT;

--CREATE TABLE  TMP_LIS_1028  AS
DELETE FROM TMP_LIS_1028;
COMMIT;
INSERT INTO TMP_LIS_1028
SELECT   A.CONTNO, --保单号
       C.RISKCODE, --险种代码
       C.GETMONEY --退保总金额
  FROM LIS.LPEDORITEM A
 INNER JOIN LIS.LPEDORAPP B
    ON A.EDORACCEPTNO = B.EDORACCEPTNO
 INNER JOIN LIS.LJAGETENDORSE C
    ON A.EDORNO = C.ENDORSEMENTNO --批单号码
 WHERE A.EDORTYPE = 'CT'
   AND A.EDORSTATE = '0' --确认生效
   AND B.PREINPUTFLAG = '1' --预录入保全标记
   AND A.EDORVALIDATE = TRUNC(SYSDATE)-1
   AND EXISTS (SELECT 1
          FROM LIS.LCCONT N
         WHERE A.CONTNO = N.CONTNO
           AND N.APPFLAG IN ('1', '4') --承包和终止保单
           AND N.CONTTYPE = '1' --个单
           AND N.MANAGECOM LIKE '8647%');
COMMIT;

SELECT  NVL(A.POLICY_CODE, B.CONTNO) AS 保单号,
       NVL(A.BUSI_PROD_CODE, B.RISKCODE) AS 险种代码,
       A.SURRENDER_AMOUNT AS 新核心退保总金额,
       B.GETMONEY AS 老核心退保总金额,
       A.SURRENDER_AMOUNT - B.GETMONEY AS 差异
  FROM TMP_NCS_1028 A
  FULL JOIN TMP_LIS_1028 B
    ON TRIM(A.POLICY_CODE) = TRIM(B.CONTNO)
   AND TRIM(A.BUSI_PROD_CODE) = TRIM(B.RISKCODE);

