
SELECT COUNT(TCP.ITEM_ID) AS 批处理笔数,
       SUM(TBA.BONUS_SA) AS 年度红利保额,
       SUM(TBA.ORIGIN_BONUS_SA) 分红前累计红利保额,
       SUM(TCP.BONUS_SA) 分红后累计红利保额
  FROM DEV_PAS.T_CONTRACT_PRODUCT@BINGXING_168_15 TCP
  LEFT JOIN DEV_PAS.T_BONUS_ALLOCATE@BINGXING_168_15 TBA
    ON TCP.ITEM_ID = TBA.ITEM_ID
 WHERE TCP.POLICY_ID = TBA.POLICY_ID
   AND TCP.ORGAN_CODE LIKE '8647%'
   AND TBA.BONUS_ALLOT = '1'
   AND TBA.ALLOCATE_DUE_DATE = TRUNC(SYSDATE) - 1;

   
SELECT COUNT(TRIM(T1.DUTYCODE)) AS 老核心保单数,
       SUM(T1.BONUSAMNT) AS 年度红利保额,
       SUM(T1.AVAILABLEAMNT - T1.BASEAMNT - T1.BONUSAMNT) AS 分红前累计红利保额,
       SUM(T1.AVAILABLEAMNT - T1.BASEAMNT) AS 分红后累计红利保额
  FROM LIS.LOENGBONUSPOL T1
  LEFT JOIN LIS.LCCONT T2
    ON T1.CONTNO = T2.CONTNO
 WHERE T2.CONTTYPE = '1'
   AND T2.APPFLAG IN ('1', '4')
   AND T2.MANAGECOM LIKE '8647%'
   AND T1.DISPATCHTYPE <> '2'
   AND T1.SDISPATCHDATE = TRUNC(SYSDATE) - 1;


   
/********************************************************** 明细 *******************************************************/

DELETE FROM TMP_NCS_1002;
COMMIT;
INSERT INTO TMP_NCS_1002
--CREATE TABLE TMP_NCS_1002  AS
SELECT TBA.POLICY_CODE, --保单号
       TCP.PRODUCT_CODE, --责任组代码
       TO_CHAR(TBA.ALLOCATE_DUE_DATE, 'yyyy') - 1  FISCALYEAR, --会计年度
       TBA.BONUS_RATE, -- 红利率
       TBA.BONUS_SA, -- 年度红利保额
       TBA.ORIGIN_BONUS_SA, --分红前累计红利保额
       TCP.BONUS_SA BONUS_SA1, --分红后累计红利保额
       TBA.RATE_RELEASE_DATE, --红利公布日
       TBA.ALLOCATE_DUE_DATE --红利应分配日期
  FROM DEV_PAS.T_CONTRACT_PRODUCT@BINGXING_168_15 TCP
  LEFT JOIN DEV_PAS.T_BONUS_ALLOCATE@BINGXING_168_15 TBA
    ON TCP.ITEM_ID = TBA.ITEM_ID
 WHERE TCP.POLICY_ID = TBA.POLICY_ID
   AND TCP.ORGAN_CODE LIKE '8647%'
   AND TBA.BONUS_ALLOT = '1'
   AND TBA.ALLOCATE_DUE_DATE = TRUNC(SYSDATE)-1
 ORDER BY 1;
 COMMIT;


DELETE FROM TMP_LIS_1002;
COMMIT;
INSERT INTO TMP_LIS_1002
--CREATE TABLE  TMP_LIS_1002   AS
SELECT TRIM(T1.CONTNO) AS CONTNO,
       T1.DUTYCODE AS DUTYCODE,
       TRIM(T1.FISCALYEAR) AS FISCALYEAR,
       T1.BONUSRATE AS BONUSRATE,
       T1.BONUSAMNT AS BONUSAMNT,
       SUM(T1.AVAILABLEAMNT - T1.BASEAMNT - T1.BONUSAMNT),
       SUM(T1.AVAILABLEAMNT - T1.BASEAMNT),
       T1.BONUSMAKEDATE AS BONUSMAKEDATE,
       T1.SDISPATCHDATE AS SDISPATCHDATE
  FROM LIS.LOENGBONUSPOL T1
  LEFT JOIN LIS.LCCONT T2
    ON T1.CONTNO = T2.CONTNO
 WHERE T2.CONTTYPE = '1'
   AND T2.APPFLAG IN ('1', '4')
   AND T2.MANAGECOM LIKE '8647%'
   AND T1.DISPATCHTYPE <> '2'
   AND T1.SDISPATCHDATE = TRUNC(SYSDATE) - 1
 GROUP BY TRIM(T1.CONTNO),
          T1.DUTYCODE,
          TRIM(T1.FISCALYEAR),
          T1.BONUSRATE,
          T1.BONUSAMNT,
          T1.BONUSMAKEDATE,
          T1.SDISPATCHDATE
 ORDER BY TRIM(T1.CONTNO);
COMMIT;"

SELECT NVL(TRIM(T2.POLICY_CODE), TRIM(T1.CONTNO)) AS 保单号,
       NVL(T2.PRODUCT_CODE, TRIM(T1.DUTYCODE)) AS 责任组代码,
       NVL(TRIM(T1.FISCALYEAR), T2.FISCALYEAR) AS 会计年度,
       NVL(TRIM(T1.BONUSRATE), T2.BONUS_RATE) AS 红利率,
       SUM(NVL(T2.BONUS_SA, 0)) AS 年度红利保额新核心,
       SUM(NVL(T1.BONUSAMNT, 0)) AS 年度红利保额老核心,
       SUM(NVL(T2.ORIGIN_BONUS_SA, 0)) AS 分红前累计红利保额新核心,
       SUM(NVL(T1.LASTYEARSUMBONUSAMNT, 0)) AS 分红前累计红利保额老核心,
       SUM(NVL(T2.BONUS_SA1, 0)) AS 分红后累计红利保额新核心,
       SUM(NVL(T1.SUMBONUSAMNT, 0)) AS 分红后累计红利保额老核心,
       T1.BONUSMAKEDATE AS 红利公布日,
       T1.SDISPATCHDATE AS 红利应分配日期,
       SUM(NVL(T2.BONUS_SA, 0) - NVL(T1.BONUSAMNT, 0)) AS 年度红利保额差异,
       SUM(NVL(T2.ORIGIN_BONUS_SA, 0) - NVL(T1.LASTYEARSUMBONUSAMNT, 0)) AS 分红前累计红利保额差异,
       SUM(NVL(T2.BONUS_SA1, 0) - NVL(T1.SUMBONUSAMNT, 0)) AS 分红后累计红利保额差异
  FROM TMP_LIS_1002 T1
  FULL JOIN TMP_NCS_1002 T2
    ON TRIM(T1.CONTNO) = TRIM(T2.POLICY_CODE)
 GROUP BY NVL(TRIM(T2.POLICY_CODE), TRIM(T1.CONTNO)),
          NVL(T2.PRODUCT_CODE, TRIM(T1.DUTYCODE)),
          NVL(TRIM(T1.FISCALYEAR), T2.FISCALYEAR),
          NVL(TRIM(T1.BONUSRATE), T2.BONUS_RATE),
          T1.BONUSMAKEDATE,
          T1.SDISPATCHDATE;





