SELECT   COUNT(1) AS 新核心保单件数,
       SUM(T.FEE_AMOUNT) + NVL(SUM(RENEWAL_PREM), 0) AS 新核心保费总金额
  FROM (SELECT TPA.POLICY_CODE, SUM(TPA.FEE_AMOUNT) FEE_AMOUNT, RENEWAL_PREM
          FROM DEV_PAS.T_PREM_ARAP@BINGXING_168_15 TPA
          LEFT JOIN (SELECT TBD.POLICY_CODE,
                           SUM(TRB.RENEWAL_PREM) RENEWAL_PREM
                      FROM DEV_PAS.T_RENEWAL_BILLING@BINGXING_168_15 TRB
                      LEFT JOIN DEV_PAS.T_CONTRACT_BUSI_PROD@BINGXING_168_15 TBD
                        ON TBD.POLICY_ID = TRB.POLICY_ID
                       AND TBD.BUSI_ITEM_ID = TRB.BUSI_ITEM_ID
                     WHERE TRB.BILLING_DATE = TRUNC(SYSDATE) - 1 + 50
                       AND TBD.RENEW_DECISION IS NULL
                       AND TBD.RENEWAL_STATE = 1
                       AND TBD.GURNT_RENEW_START IS NULL
                     GROUP BY TBD.POLICY_CODE) T
            ON TPA.POLICY_CODE = T.POLICY_CODE
         WHERE TPA.FEE_TYPE IN ('G003100000',
                                'G003010000',
                                'G003020100',
                                'G003020200',
                                'G003030100',
                                'G003030200',
                                'G003040100',
                                'G003040200')
           AND (TPA.FEE_STATUS = '00' OR TPA.FEE_STATUS = '20')
           AND TPA.BRANCH_CODE = '8647'
           AND TPA.DUE_TIME = TRUNC(SYSDATE) - 1 + 50
         GROUP BY TPA.POLICY_CODE, RENEWAL_PREM --查询续期、续保（包含进人工核保）
        UNION ALL
        SELECT T.POLICY_CODE, NULL FEE_AMOUNT, RENEWAL_PREM
          FROM (SELECT TBD.POLICY_CODE, SUM(TRB.RENEWAL_PREM) RENEWAL_PREM
                  FROM DEV_PAS.T_RENEWAL_BILLING@BINGXING_168_15 TRB
                  LEFT JOIN DEV_PAS.T_CONTRACT_BUSI_PROD@BINGXING_168_15 TBD
                    ON TBD.POLICY_ID = TRB.POLICY_ID
                   AND TBD.BUSI_ITEM_ID = TRB.BUSI_ITEM_ID
                 WHERE TRB.BILLING_DATE = TRUNC(SYSDATE) - 1 + 50
                   AND (TBD.RENEW_DECISION IS NULL OR TBD.RENEW_DECISION = 3)
                   AND TBD.RENEWAL_STATE = 1
                   AND TBD.GURNT_RENEW_START IS NULL
                 GROUP BY TBD.POLICY_CODE) T
         WHERE 1 = 1
           AND NOT EXISTS
         (SELECT 1
                  FROM DEV_PAS.T_PREM_ARAP@BINGXING_168_15 A
                 WHERE (A.FEE_STATUS = 00 OR A.FEE_STATUS = 20)
                   AND A.BRANCH_CODE = '8647'
                   AND A.DUE_TIME = TRUNC(SYSDATE) - 1 + 50
                   AND A.POLICY_CODE = T.POLICY_CODE)
         ORDER BY POLICY_CODE) T;

SELECT   COUNT(DISTINCT A.CONTNO) AS 笔数, SUM(A.SUMACTUPAYMONEY) AS 金额
  FROM LIS.LJSPAYPERSON A
  JOIN LIS.LCCONT B
    ON A.CONTNO = B.CONTNO
 WHERE B.CONTTYPE = '1'
   AND B.APPFLAG = '1'
   AND PAYCOUNT > 1
   AND PAYTYPE = 'ZC'
   AND (GETNOTICENO IS NULL OR GETNOTICENO NOT LIKE 'CLMUW%')
   AND LASTPAYTODATE = TRUNC(SYSDATE)-1 + 50
   AND B.MANAGECOM LIKE '8647%';
   
/**************************************************************** 明细 ****************************************************************/
--CREATE TABLE  TMP_NCS_1023  AS
DELETE FROM TMP_NCS_1023;
COMMIT;
INSERT INTO TMP_NCS_1023
SELECT    TPA.POLICY_CODE, -- 保单号
       SUM(TPA.FEE_AMOUNT) FEE_AMOUNT, --应收应付金额
       RENEWAL_PREM --新核心进核保重算保费金额
  FROM DEV_PAS.T_PREM_ARAP@BINGXING_168_15 TPA
  LEFT JOIN (SELECT TBD.POLICY_CODE, SUM(TRB.RENEWAL_PREM) RENEWAL_PREM
               FROM DEV_PAS.T_RENEWAL_BILLING@BINGXING_168_15 TRB
               LEFT JOIN DEV_PAS.T_CONTRACT_BUSI_PROD@BINGXING_168_15 TBD
                 ON TBD.POLICY_ID = TRB.POLICY_ID
                AND TBD.BUSI_ITEM_ID = TRB.BUSI_ITEM_ID
              WHERE TRB.BILLING_DATE = TRUNC(SYSDATE)-1 + 50
                AND TBD.RENEW_DECISION IS NULL
                AND TBD.RENEWAL_STATE = 1
                AND TBD.GURNT_RENEW_START IS NULL
              GROUP BY TBD.POLICY_CODE) T
    ON TPA.POLICY_CODE = T.POLICY_CODE
 WHERE TPA.FEE_TYPE IN ('G003100000',
                        'G003010000',
                        'G003020100',
                        'G003020200',
                        'G003030100',
                        'G003030200',
                        'G003040100',
                        'G003040200')
   AND (TPA.FEE_STATUS = '00' OR TPA.FEE_STATUS = '20')
   AND TPA.BRANCH_CODE LIKE '8647%'
   AND TPA.DUE_TIME = TRUNC(SYSDATE)-1 + 50
 GROUP BY TPA.POLICY_CODE, RENEWAL_PREM --查询续期、续保（包含进人工核保）
UNION ALL
SELECT    T.POLICY_CODE, NULL FEE_AMOUNT, RENEWAL_PREM
  FROM (SELECT TBD.POLICY_CODE, SUM(TRB.RENEWAL_PREM) RENEWAL_PREM
          FROM DEV_PAS.T_RENEWAL_BILLING@BINGXING_168_15 TRB
          LEFT JOIN DEV_PAS.T_CONTRACT_BUSI_PROD@BINGXING_168_15 TBD
            ON TBD.POLICY_ID = TRB.POLICY_ID
           AND TBD.BUSI_ITEM_ID = TRB.BUSI_ITEM_ID
         WHERE TRB.BILLING_DATE = TRUNC(SYSDATE)-1 + 50
           AND (TBD.RENEW_DECISION IS NULL OR TBD.RENEW_DECISION = 3)
           AND TBD.RENEWAL_STATE = 1
           AND TBD.GURNT_RENEW_START IS NULL
         GROUP BY TBD.POLICY_CODE) T
 WHERE 1 = 1
   AND NOT EXISTS (SELECT 1
          FROM DEV_PAS.T_PREM_ARAP@BINGXING_168_15 A
         WHERE (A.FEE_STATUS = 00 OR A.FEE_STATUS = 20)
           AND A.BRANCH_CODE LIKE '8647%'
           AND A.DUE_TIME = TRUNC(SYSDATE)-1 + 50
           AND A.POLICY_CODE = T.POLICY_CODE)
 ORDER BY 1;
COMMIT;

--CREATE TABLE  TMP_LIS_1023  AS
DELETE FROM TMP_LIS_1023;
COMMIT;
INSERT INTO TMP_LIS_1023
SELECT    A.CONTNO AS CONTNO, SUM(A.SUMACTUPAYMONEY) AS SUMACTUPAYMONEY
  FROM LIS.LJSPAYPERSON A
  JOIN LIS.LCCONT B
    ON A.CONTNO = B.CONTNO
 WHERE B.CONTTYPE = '1'
   AND B.APPFLAG = '1'
   AND PAYCOUNT > 1
   AND PAYTYPE = 'ZC'
   AND (GETNOTICENO IS NULL OR GETNOTICENO NOT LIKE 'CLMUW%')
   AND LASTPAYTODATE = TRUNC(SYSDATE)-1 + 50
   AND B.MANAGECOM LIKE '8647%'
 GROUP BY A.CONTNO, A.LASTPAYTODATE
 ORDER BY A.CONTNO;
 COMMIT;
 
SELECT    NVL(TRIM(T2.POLICY_CODE), TRIM(T1.CONTNO)) AS 保单号,
       NVL(T2.FEE_AMOUNT, 0) AS 新核心应收应付金额,
       NVL(T2.RENEWAL_PREM, 0) AS 新核心进核保重算保费金额,
       NVL(T1.SUMACTUPAYMONEY, 0) AS 老核心应收应付金额,
       (NVL(T2.FEE_AMOUNT, 0) + NVL(T2.RENEWAL_PREM, 0)) -
       NVL(T1.SUMACTUPAYMONEY, 0) AS 差异值
  FROM TMP_LIS_1023 T1
  FULL JOIN TMP_NCS_1023 T2
    ON TRIM(T1.CONTNO) = TRIM(T2.POLICY_CODE)
 ORDER BY T2.POLICY_CODE;



