/**新核心：**/

  /**保全申请明细：**/
SELECT TCA.APPLY_TIME 统计日期,TCAC.ORGAN_CODE 管理机构,TCA.APPLY_CODE 申请号,TCAC.ACCEPT_CODE 受理号,TCAC.SERVICE_CODE 保全项
FROM APP___PAS__DBUSER.T_CS_ACCEPT_CHANGE TCAC 
LEFT JOIN APP___PAS__DBUSER.T_CS_APPLICATION/*保全申请表*/ TCA
     ON TCAC.CHANGE_ID = TCA.CHANGE_ID
WHERE TO_CHAR(TCA.APPLY_TIME, 'YYYYMMDD') = '20151231' --生效日期
AND TCAC.ORGAN_CODE LIKE '8647%' --机构
ORDER BY TCA.APPLY_CODE;
  /** 保全生效明细：**/
SELECT L.VALIDATE_TIME 统计时间,L.ORGAN_CODE 管理机构,L.ACCEPT_CODE 受理号,L.SERVICE_CODE 保全项
FROM APP___PAS__DBUSER.T_CS_ACCEPT_CHANGE L
WHERE TO_CHAR(L.VALIDATE_TIME, 'YYYYMMDD') = '20151231' --生效日期
AND L.ORGAN_CODE LIKE '8647%' --机构
ORDER BY L.ACCEPT_CODE;
  /**保全应收付明细：**/
select TCPA.POLICY_CODE 保单号,TCPA.ORGAN_CODE 管理机构,TCPA.FEE_AMOUNT 金额,TCPA.FEE_TYPE 补退费标志/*补退费类型32-退41-收*/
       from APP___PAS__DBUSER.T_CS_PREM_ARAP TCPA
WHERE TCPA.ORGAN_CODE LIKE '8647%'
AND TO_CHAR(TCPA.FINISH_TIME, 'YYYYMMDD') = '20151231'--收付费业务核销时间
ORDER BY TCPA.POLICY_CODE;
